version: '3.8'

services:
  cobank-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cobank-app
    image: cobank-app-image
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/cobankdb
      SPRING_DATASOURCE_USERNAME: cobankuser
      SPRING_DATASOURCE_PASSWORD: cobankpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_FLYWAY_ENABLED: true

  postgres-db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: cobankdb
      POSTGRES_USER: cobankuser
      POSTGRES_PASSWORD: cobankpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: