services:
  cobank-app:
    image: eclipse-temurin:17-jdk
    container_name: cobank-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
